anchor_version = "0.25.0"

[workspace]
members = [
    ".",
]

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[programs.mainnet]
dex_v4 = "srmv4uTCPF81hWDaPyEN2mLZ8XbvzuEM6LsAxR8NpjU"